import Foundation
import Network
import Security
import os.log

// MARK: - HTTPS / TLS Support
// Adds an optional TLS listener alongside the plain HTTP listener.
// The TLS identity is loaded from a PKCS12 file generated by the
// macOS host app's TLSCertificateManager.

public struct HTTPSConfig: Sendable {
    public let port: Int
    public let identityPath: String

    public init(port: Int, identityPath: String) {
        self.port = port
        self.identityPath = identityPath
    }
}

extension QuotaHTTPServer {

    func startHTTPSListener(config: HTTPSConfig, host: NWEndpoint.Host) async throws -> NWListener {
        let (identity, chain) = try loadTLSIdentity(from: config.identityPath)

        let tlsOptions = NWProtocolTLS.Options()
        let secIdentity: sec_identity_t
        if !chain.isEmpty {
            guard let id = sec_identity_create_with_certificates(identity, chain as CFArray) else {
                throw TLSSetupError.identityCreationFailed
            }
            secIdentity = id
        } else {
            guard let id = sec_identity_create(identity) else {
                throw TLSSetupError.identityCreationFailed
            }
            secIdentity = id
        }
        sec_protocol_options_set_local_identity(
            tlsOptions.securityProtocolOptions,
            secIdentity
        )

        let params = NWParameters(tls: tlsOptions, tcp: .init())
        guard let httpsPort = NWEndpoint.Port(rawValue: UInt16(config.port)) else {
            throw QuotaHTTPServerError.invalidPort(config.port)
        }
        params.requiredLocalEndpoint = NWEndpoint.hostPort(host: host, port: httpsPort)

        let listener = try NWListener(using: params)
        listener.newConnectionHandler = { [weak self] connection in
            guard let self else { return }
            Task { await self.handleConnection(connection) }
        }

        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
            let lock = NSLock()
            var resolved = false
            listener.stateUpdateHandler = { state in
                lock.lock()
                defer { lock.unlock() }
                guard !resolved else { return }
                switch state {
                case .ready:
                    resolved = true
                    continuation.resume()
                case .failed(let error):
                    resolved = true
                    continuation.resume(throwing: error)
                case .cancelled:
                    resolved = true
                    continuation.resume(throwing: CancellationError())
                default:
                    break
                }
            }
            listener.start(queue: .global())
        }

        httpLog.info("HTTPS listener ready on port \(config.port)")
        return listener
    }

    // MARK: - Identity Loading

    private func loadTLSIdentity(from path: String) throws -> (SecIdentity, [SecCertificate]) {
        let data = try Data(contentsOf: URL(fileURLWithPath: path))

        let password = "aiusage-proxy-tls"
        var importItems: CFArray?
        let importParams: [String: Any] = [
            kSecImportExportPassphrase as String: password
        ]
        let status = SecPKCS12Import(data as CFData, importParams as CFDictionary, &importItems)

        guard status == errSecSuccess else {
            throw TLSSetupError.identityLoadFailed(status)
        }

        guard let array = importItems as? [[String: Any]],
              let first = array.first else {
            throw TLSSetupError.identityLoadFailed(errSecItemNotFound)
        }

        let chain = first[kSecImportItemCertChain as String] as? [SecCertificate] ?? []

        if let identity = first[kSecImportItemIdentity as String] {
            return (identity as! SecIdentity, chain) // swiftlint:disable:this force_cast
        }

        guard let cert = chain.first else {
            throw TLSSetupError.identityLoadFailed(errSecItemNotFound)
        }

        var identityRef: SecIdentity?
        let matchStatus = SecIdentityCreateWithCertificate(nil, cert, &identityRef)
        guard matchStatus == errSecSuccess, let identity = identityRef else {
            throw TLSSetupError.identityLoadFailed(matchStatus)
        }
        return (identity, chain)
    }
}

// MARK: - TLS Errors

enum TLSSetupError: LocalizedError {
    case identityLoadFailed(OSStatus)
    case identityCreationFailed

    var errorDescription: String? {
        switch self {
        case .identityLoadFailed(let status):
            return "Failed to load TLS identity (OSStatus: \(status))"
        case .identityCreationFailed:
            return "Failed to create sec_identity_t from SecIdentity"
        }
    }
}
