import Foundation
import Network
import Security
import os.log

// MARK: - HTTPS / TLS Support
// Adds an optional TLS listener alongside the plain HTTP listener.
// The TLS identity is loaded from a PKCS12 file generated by the
// macOS host app's TLSCertificateManager.

public struct HTTPSConfig: Sendable {
    public let port: Int
    public let identityPath: String

    public init(port: Int, identityPath: String) {
        self.port = port
        self.identityPath = identityPath
    }
}

extension QuotaHTTPServer {

    func startHTTPSListener(config: HTTPSConfig, host: NWEndpoint.Host) async throws -> NWListener {
        let identity = try loadTLSIdentity(from: config.identityPath)

        let tlsOptions = NWProtocolTLS.Options()
        guard let secIdentity = sec_identity_create(identity) else {
            throw TLSSetupError.identityCreationFailed
        }
        sec_protocol_options_set_local_identity(
            tlsOptions.securityProtocolOptions,
            secIdentity
        )

        let params = NWParameters(tls: tlsOptions, tcp: .init())
        guard let httpsPort = NWEndpoint.Port(rawValue: UInt16(config.port)) else {
            throw QuotaHTTPServerError.invalidPort(config.port)
        }
        params.requiredLocalEndpoint = NWEndpoint.hostPort(host: host, port: httpsPort)

        let listener = try NWListener(using: params)
        listener.newConnectionHandler = { [weak self] connection in
            guard let self else { return }
            Task { await self.handleConnection(connection) }
        }

        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
            let lock = NSLock()
            var resolved = false
            listener.stateUpdateHandler = { state in
                lock.lock()
                defer { lock.unlock() }
                guard !resolved else { return }
                switch state {
                case .ready:
                    resolved = true
                    continuation.resume()
                case .failed(let error):
                    resolved = true
                    continuation.resume(throwing: error)
                case .cancelled:
                    resolved = true
                    continuation.resume(throwing: CancellationError())
                default:
                    break
                }
            }
            listener.start(queue: .global())
        }

        httpLog.info("HTTPS listener ready on port \(config.port)")
        return listener
    }

    // MARK: - Identity Loading

    private func loadTLSIdentity(from path: String) throws -> SecIdentity {
        let data = try Data(contentsOf: URL(fileURLWithPath: path))

        var items: CFArray?
        let options: NSDictionary = [kSecImportExportPassphrase: "aiusage-proxy-tls"]
        let status = SecPKCS12Import(data as CFData, options, &items)

        guard status == errSecSuccess,
              let array = items as? [[String: Any]],
              let first = array.first,
              let identity = first[kSecImportItemIdentity as String] else {
            throw TLSSetupError.identityLoadFailed(status)
        }

        // swiftlint:disable:next force_cast
        return identity as! SecIdentity
    }
}

// MARK: - TLS Errors

enum TLSSetupError: LocalizedError {
    case identityLoadFailed(OSStatus)
    case identityCreationFailed

    var errorDescription: String? {
        switch self {
        case .identityLoadFailed(let status):
            return "Failed to load TLS identity (OSStatus: \(status))"
        case .identityCreationFailed:
            return "Failed to create sec_identity_t from SecIdentity"
        }
    }
}
